/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 57
#define LARGE_STATE_COUNT 9
#define SYMBOL_COUNT 31
#define ALIAS_COUNT 0
#define TOKEN_COUNT 18
#define EXTERNAL_TOKEN_COUNT 1
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  aux_sym_heading_token1 = 1,
  sym_command_name = 2,
  anon_sym_LBRACE = 3,
  anon_sym_RBRACE = 4,
  anon_sym_LBRACK = 5,
  anon_sym_RBRACK = 6,
  anon_sym_LPAREN = 7,
  aux_sym_link_url_token1 = 8,
  anon_sym_RPAREN = 9,
  anon_sym_STAR = 10,
  anon_sym__ = 11,
  sym_code_span = 12,
  sym_inline_math = 13,
  sym_display_math = 14,
  sym_comment = 15,
  sym_text = 16,
  sym_code_block = 17,
  sym_source_file = 18,
  sym__node = 19,
  sym_heading = 20,
  sym_command = 21,
  sym_command_arg = 22,
  sym_link = 23,
  sym_link_text = 24,
  sym_link_url = 25,
  sym_bold = 26,
  sym_italic = 27,
  aux_sym_source_file_repeat1 = 28,
  aux_sym_heading_repeat1 = 29,
  aux_sym_link_text_repeat1 = 30,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym_heading_token1] = "heading_token1",
  [sym_command_name] = "command_name",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LPAREN] = "(",
  [aux_sym_link_url_token1] = "link_url_token1",
  [anon_sym_RPAREN] = ")",
  [anon_sym_STAR] = "*",
  [anon_sym__] = "_",
  [sym_code_span] = "code_span",
  [sym_inline_math] = "inline_math",
  [sym_display_math] = "display_math",
  [sym_comment] = "comment",
  [sym_text] = "text",
  [sym_code_block] = "code_block",
  [sym_source_file] = "source_file",
  [sym__node] = "_node",
  [sym_heading] = "heading",
  [sym_command] = "command",
  [sym_command_arg] = "command_arg",
  [sym_link] = "link",
  [sym_link_text] = "link_text",
  [sym_link_url] = "link_url",
  [sym_bold] = "bold",
  [sym_italic] = "italic",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_heading_repeat1] = "heading_repeat1",
  [aux_sym_link_text_repeat1] = "link_text_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym_heading_token1] = aux_sym_heading_token1,
  [sym_command_name] = sym_command_name,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [aux_sym_link_url_token1] = aux_sym_link_url_token1,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym__] = anon_sym__,
  [sym_code_span] = sym_code_span,
  [sym_inline_math] = sym_inline_math,
  [sym_display_math] = sym_display_math,
  [sym_comment] = sym_comment,
  [sym_text] = sym_text,
  [sym_code_block] = sym_code_block,
  [sym_source_file] = sym_source_file,
  [sym__node] = sym__node,
  [sym_heading] = sym_heading,
  [sym_command] = sym_command,
  [sym_command_arg] = sym_command_arg,
  [sym_link] = sym_link,
  [sym_link_text] = sym_link_text,
  [sym_link_url] = sym_link_url,
  [sym_bold] = sym_bold,
  [sym_italic] = sym_italic,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_heading_repeat1] = aux_sym_heading_repeat1,
  [aux_sym_link_text_repeat1] = aux_sym_link_text_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_heading_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_command_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_link_url_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym__] = {
    .visible = true,
    .named = false,
  },
  [sym_code_span] = {
    .visible = true,
    .named = true,
  },
  [sym_inline_math] = {
    .visible = true,
    .named = true,
  },
  [sym_display_math] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_code_block] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__node] = {
    .visible = false,
    .named = true,
  },
  [sym_heading] = {
    .visible = true,
    .named = true,
  },
  [sym_command] = {
    .visible = true,
    .named = true,
  },
  [sym_command_arg] = {
    .visible = true,
    .named = true,
  },
  [sym_link] = {
    .visible = true,
    .named = true,
  },
  [sym_link_text] = {
    .visible = true,
    .named = true,
  },
  [sym_link_url] = {
    .visible = true,
    .named = true,
  },
  [sym_bold] = {
    .visible = true,
    .named = true,
  },
  [sym_italic] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_heading_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_link_text_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 2,
  [7] = 5,
  [8] = 4,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 9,
  [13] = 10,
  [14] = 11,
  [15] = 15,
  [16] = 15,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 18,
  [22] = 22,
  [23] = 23,
  [24] = 23,
  [25] = 25,
  [26] = 19,
  [27] = 17,
  [28] = 22,
  [29] = 20,
  [30] = 25,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 18,
  [35] = 20,
  [36] = 36,
  [37] = 36,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 39,
  [47] = 45,
  [48] = 48,
  [49] = 40,
  [50] = 39,
  [51] = 45,
  [52] = 41,
  [53] = 43,
  [54] = 48,
  [55] = 41,
  [56] = 43,
};

static const TSCharacterRange sym_text_character_set_1[] = {
  {0, 0x08}, {0x0b, 0x1f}, {'!', '"'}, {'%', '\''}, {'+', '.'}, {'0', '?'}, {'A', 'Z'}, {'^', '^'},
  {'a', 'z'}, {'|', '|'}, {'~', 0x10ffff},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(20);
      ADVANCE_MAP(
        '#', 10,
        '$', 11,
        '(', 27,
        ')', 30,
        '*', 31,
        '/', 15,
        '@', 17,
        '[', 25,
        ']', 26,
        '_', 32,
        '`', 16,
        '{', 23,
        '}', 24,
      );
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '\r', 37,
        '#', 10,
        '$', 11,
        '*', 31,
        '/', 15,
        '@', 17,
        '[', 25,
        '_', 32,
        '`', 16,
        '{', 23,
      );
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == ' ') SKIP(1);
      if (lookahead != 0 &&
          (lookahead < '(' || '*' < lookahead) &&
          (lookahead < '[' || ']' < lookahead) &&
          lookahead != '}') ADVANCE(41);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '\r', 38,
        '#', 10,
        '$', 11,
        '*', 31,
        '/', 15,
        '@', 17,
        '[', 25,
        '_', 32,
        '`', 16,
        '{', 23,
        '}', 24,
      );
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == ' ') SKIP(2);
      if (lookahead != 0 &&
          (lookahead < '(' || '*' < lookahead) &&
          (lookahead < '[' || ']' < lookahead)) ADVANCE(41);
      END_STATE();
    case 3:
      if (lookahead == '\r') ADVANCE(39);
      if (lookahead == '*') ADVANCE(31);
      if (lookahead == ']') ADVANCE(26);
      if (lookahead == '_') ADVANCE(32);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == ' ') SKIP(3);
      if ((!eof && set_contains(sym_text_character_set_1, 11, lookahead))) ADVANCE(41);
      END_STATE();
    case 4:
      if (lookahead == '\r') ADVANCE(40);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == ' ') SKIP(4);
      if ((!eof && set_contains(sym_text_character_set_1, 11, lookahead))) ADVANCE(41);
      END_STATE();
    case 5:
      if (lookahead == ' ') ADVANCE(21);
      END_STATE();
    case 6:
      if (lookahead == ' ') ADVANCE(21);
      if (lookahead == '#') ADVANCE(5);
      END_STATE();
    case 7:
      if (lookahead == ' ') ADVANCE(21);
      if (lookahead == '#') ADVANCE(6);
      END_STATE();
    case 8:
      if (lookahead == ' ') ADVANCE(21);
      if (lookahead == '#') ADVANCE(7);
      END_STATE();
    case 9:
      if (lookahead == ' ') ADVANCE(21);
      if (lookahead == '#') ADVANCE(8);
      END_STATE();
    case 10:
      if (lookahead == ' ') ADVANCE(21);
      if (lookahead == '#') ADVANCE(9);
      END_STATE();
    case 11:
      if (lookahead == '$') ADVANCE(18);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(12);
      END_STATE();
    case 12:
      if (lookahead == '$') ADVANCE(34);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(12);
      END_STATE();
    case 13:
      if (lookahead == '$') ADVANCE(14);
      if (lookahead != 0) ADVANCE(13);
      END_STATE();
    case 14:
      if (lookahead == '$') ADVANCE(35);
      END_STATE();
    case 15:
      if (lookahead == '/') ADVANCE(36);
      END_STATE();
    case 16:
      if (lookahead == '`') ADVANCE(33);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(16);
      END_STATE();
    case 17:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 18:
      if (lookahead != 0 &&
          lookahead != '$') ADVANCE(13);
      END_STATE();
    case 19:
      if (eof) ADVANCE(20);
      ADVANCE_MAP(
        '\r', 37,
        '#', 10,
        '$', 11,
        '*', 31,
        '/', 15,
        '@', 17,
        '[', 25,
        '_', 32,
        '`', 16,
        '{', 23,
      );
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == ' ') SKIP(19);
      if (lookahead != 0 &&
          (lookahead < '(' || '*' < lookahead) &&
          (lookahead < '[' || ']' < lookahead) &&
          lookahead != '}') ADVANCE(41);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym_heading_token1);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_command_name);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym_link_url_token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(28);
      if (lookahead != 0 &&
          lookahead != ')') ADVANCE(29);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym_link_url_token1);
      if (lookahead != 0 &&
          lookahead != ')') ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym__);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_code_span);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_inline_math);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_display_math);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(36);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_text);
      ADVANCE_MAP(
        '\r', 37,
        '#', 10,
        '$', 11,
        '*', 31,
        '/', 15,
        '@', 17,
        '[', 25,
        '_', 32,
        '`', 16,
        '{', 23,
      );
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == ' ') SKIP(1);
      if (lookahead != 0 &&
          (lookahead < '(' || '*' < lookahead) &&
          (lookahead < '[' || ']' < lookahead) &&
          lookahead != '}') ADVANCE(41);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_text);
      ADVANCE_MAP(
        '\r', 38,
        '#', 10,
        '$', 11,
        '*', 31,
        '/', 15,
        '@', 17,
        '[', 25,
        '_', 32,
        '`', 16,
        '{', 23,
        '}', 24,
      );
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == ' ') SKIP(2);
      if (lookahead != 0 &&
          (lookahead < '(' || '*' < lookahead) &&
          (lookahead < '[' || ']' < lookahead)) ADVANCE(41);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '\r') ADVANCE(39);
      if (lookahead == '*') ADVANCE(31);
      if (lookahead == ']') ADVANCE(26);
      if (lookahead == '_') ADVANCE(32);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == ' ') SKIP(3);
      if ((!eof && set_contains(sym_text_character_set_1, 11, lookahead))) ADVANCE(41);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '\r') ADVANCE(40);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == ' ') SKIP(4);
      if ((!eof && set_contains(sym_text_character_set_1, 11, lookahead))) ADVANCE(41);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_text);
      if ((!eof && set_contains(sym_text_character_set_1, 11, lookahead))) ADVANCE(41);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 19, .external_lex_state = 1},
  [2] = {.lex_state = 19, .external_lex_state = 1},
  [3] = {.lex_state = 19, .external_lex_state = 1},
  [4] = {.lex_state = 2, .external_lex_state = 1},
  [5] = {.lex_state = 2, .external_lex_state = 1},
  [6] = {.lex_state = 2, .external_lex_state = 1},
  [7] = {.lex_state = 2, .external_lex_state = 1},
  [8] = {.lex_state = 2, .external_lex_state = 1},
  [9] = {.lex_state = 19, .external_lex_state = 1},
  [10] = {.lex_state = 19, .external_lex_state = 1},
  [11] = {.lex_state = 19, .external_lex_state = 1},
  [12] = {.lex_state = 2, .external_lex_state = 1},
  [13] = {.lex_state = 2, .external_lex_state = 1},
  [14] = {.lex_state = 2, .external_lex_state = 1},
  [15] = {.lex_state = 19, .external_lex_state = 1},
  [16] = {.lex_state = 2, .external_lex_state = 1},
  [17] = {.lex_state = 19, .external_lex_state = 1},
  [18] = {.lex_state = 2, .external_lex_state = 1},
  [19] = {.lex_state = 19, .external_lex_state = 1},
  [20] = {.lex_state = 19, .external_lex_state = 1},
  [21] = {.lex_state = 19, .external_lex_state = 1},
  [22] = {.lex_state = 19, .external_lex_state = 1},
  [23] = {.lex_state = 19, .external_lex_state = 1},
  [24] = {.lex_state = 2, .external_lex_state = 1},
  [25] = {.lex_state = 2, .external_lex_state = 1},
  [26] = {.lex_state = 2, .external_lex_state = 1},
  [27] = {.lex_state = 2, .external_lex_state = 1},
  [28] = {.lex_state = 2, .external_lex_state = 1},
  [29] = {.lex_state = 2, .external_lex_state = 1},
  [30] = {.lex_state = 19, .external_lex_state = 1},
  [31] = {.lex_state = 3},
  [32] = {.lex_state = 3},
  [33] = {.lex_state = 3},
  [34] = {.lex_state = 3},
  [35] = {.lex_state = 3},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 4},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 4},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 28},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 4},
  [53] = {.lex_state = 4},
  [54] = {.lex_state = 28},
  [55] = {.lex_state = 4},
  [56] = {.lex_state = 4},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym_heading_token1] = ACTIONS(1),
    [sym_command_name] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym__] = ACTIONS(1),
    [sym_code_span] = ACTIONS(1),
    [sym_inline_math] = ACTIONS(1),
    [sym_display_math] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [sym_code_block] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(44),
    [sym__node] = STATE(3),
    [sym_heading] = STATE(3),
    [sym_command] = STATE(3),
    [sym_link] = STATE(3),
    [sym_link_text] = STATE(36),
    [sym_bold] = STATE(3),
    [sym_italic] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(3),
    [aux_sym_heading_token1] = ACTIONS(5),
    [sym_command_name] = ACTIONS(7),
    [anon_sym_LBRACK] = ACTIONS(9),
    [anon_sym_STAR] = ACTIONS(11),
    [anon_sym__] = ACTIONS(13),
    [sym_code_span] = ACTIONS(15),
    [sym_inline_math] = ACTIONS(15),
    [sym_display_math] = ACTIONS(15),
    [sym_comment] = ACTIONS(15),
    [sym_text] = ACTIONS(15),
    [sym_code_block] = ACTIONS(17),
  },
  [STATE(2)] = {
    [sym__node] = STATE(2),
    [sym_heading] = STATE(2),
    [sym_command] = STATE(2),
    [sym_link] = STATE(2),
    [sym_link_text] = STATE(36),
    [sym_bold] = STATE(2),
    [sym_italic] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(19),
    [aux_sym_heading_token1] = ACTIONS(21),
    [sym_command_name] = ACTIONS(24),
    [anon_sym_LBRACK] = ACTIONS(27),
    [anon_sym_STAR] = ACTIONS(30),
    [anon_sym__] = ACTIONS(33),
    [sym_code_span] = ACTIONS(36),
    [sym_inline_math] = ACTIONS(36),
    [sym_display_math] = ACTIONS(36),
    [sym_comment] = ACTIONS(36),
    [sym_text] = ACTIONS(36),
    [sym_code_block] = ACTIONS(39),
  },
  [STATE(3)] = {
    [sym__node] = STATE(2),
    [sym_heading] = STATE(2),
    [sym_command] = STATE(2),
    [sym_link] = STATE(2),
    [sym_link_text] = STATE(36),
    [sym_bold] = STATE(2),
    [sym_italic] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(42),
    [aux_sym_heading_token1] = ACTIONS(5),
    [sym_command_name] = ACTIONS(7),
    [anon_sym_LBRACK] = ACTIONS(9),
    [anon_sym_STAR] = ACTIONS(11),
    [anon_sym__] = ACTIONS(13),
    [sym_code_span] = ACTIONS(44),
    [sym_inline_math] = ACTIONS(44),
    [sym_display_math] = ACTIONS(44),
    [sym_comment] = ACTIONS(44),
    [sym_text] = ACTIONS(44),
    [sym_code_block] = ACTIONS(46),
  },
  [STATE(4)] = {
    [sym__node] = STATE(6),
    [sym_heading] = STATE(6),
    [sym_command] = STATE(6),
    [sym_link] = STATE(6),
    [sym_link_text] = STATE(37),
    [sym_bold] = STATE(6),
    [sym_italic] = STATE(6),
    [aux_sym_source_file_repeat1] = STATE(6),
    [aux_sym_heading_token1] = ACTIONS(48),
    [sym_command_name] = ACTIONS(50),
    [anon_sym_RBRACE] = ACTIONS(52),
    [anon_sym_LBRACK] = ACTIONS(9),
    [anon_sym_STAR] = ACTIONS(54),
    [anon_sym__] = ACTIONS(56),
    [sym_code_span] = ACTIONS(58),
    [sym_inline_math] = ACTIONS(58),
    [sym_display_math] = ACTIONS(58),
    [sym_comment] = ACTIONS(58),
    [sym_text] = ACTIONS(58),
    [sym_code_block] = ACTIONS(60),
  },
  [STATE(5)] = {
    [sym__node] = STATE(4),
    [sym_heading] = STATE(4),
    [sym_command] = STATE(4),
    [sym_link] = STATE(4),
    [sym_link_text] = STATE(37),
    [sym_bold] = STATE(4),
    [sym_italic] = STATE(4),
    [aux_sym_source_file_repeat1] = STATE(4),
    [aux_sym_heading_token1] = ACTIONS(48),
    [sym_command_name] = ACTIONS(50),
    [anon_sym_RBRACE] = ACTIONS(62),
    [anon_sym_LBRACK] = ACTIONS(9),
    [anon_sym_STAR] = ACTIONS(54),
    [anon_sym__] = ACTIONS(56),
    [sym_code_span] = ACTIONS(64),
    [sym_inline_math] = ACTIONS(64),
    [sym_display_math] = ACTIONS(64),
    [sym_comment] = ACTIONS(64),
    [sym_text] = ACTIONS(64),
    [sym_code_block] = ACTIONS(66),
  },
  [STATE(6)] = {
    [sym__node] = STATE(6),
    [sym_heading] = STATE(6),
    [sym_command] = STATE(6),
    [sym_link] = STATE(6),
    [sym_link_text] = STATE(37),
    [sym_bold] = STATE(6),
    [sym_italic] = STATE(6),
    [aux_sym_source_file_repeat1] = STATE(6),
    [aux_sym_heading_token1] = ACTIONS(68),
    [sym_command_name] = ACTIONS(71),
    [anon_sym_RBRACE] = ACTIONS(74),
    [anon_sym_LBRACK] = ACTIONS(27),
    [anon_sym_STAR] = ACTIONS(76),
    [anon_sym__] = ACTIONS(79),
    [sym_code_span] = ACTIONS(82),
    [sym_inline_math] = ACTIONS(82),
    [sym_display_math] = ACTIONS(82),
    [sym_comment] = ACTIONS(82),
    [sym_text] = ACTIONS(82),
    [sym_code_block] = ACTIONS(85),
  },
  [STATE(7)] = {
    [sym__node] = STATE(8),
    [sym_heading] = STATE(8),
    [sym_command] = STATE(8),
    [sym_link] = STATE(8),
    [sym_link_text] = STATE(37),
    [sym_bold] = STATE(8),
    [sym_italic] = STATE(8),
    [aux_sym_source_file_repeat1] = STATE(8),
    [aux_sym_heading_token1] = ACTIONS(48),
    [sym_command_name] = ACTIONS(50),
    [anon_sym_RBRACE] = ACTIONS(88),
    [anon_sym_LBRACK] = ACTIONS(9),
    [anon_sym_STAR] = ACTIONS(54),
    [anon_sym__] = ACTIONS(56),
    [sym_code_span] = ACTIONS(90),
    [sym_inline_math] = ACTIONS(90),
    [sym_display_math] = ACTIONS(90),
    [sym_comment] = ACTIONS(90),
    [sym_text] = ACTIONS(90),
    [sym_code_block] = ACTIONS(92),
  },
  [STATE(8)] = {
    [sym__node] = STATE(6),
    [sym_heading] = STATE(6),
    [sym_command] = STATE(6),
    [sym_link] = STATE(6),
    [sym_link_text] = STATE(37),
    [sym_bold] = STATE(6),
    [sym_italic] = STATE(6),
    [aux_sym_source_file_repeat1] = STATE(6),
    [aux_sym_heading_token1] = ACTIONS(48),
    [sym_command_name] = ACTIONS(50),
    [anon_sym_RBRACE] = ACTIONS(94),
    [anon_sym_LBRACK] = ACTIONS(9),
    [anon_sym_STAR] = ACTIONS(54),
    [anon_sym__] = ACTIONS(56),
    [sym_code_span] = ACTIONS(58),
    [sym_inline_math] = ACTIONS(58),
    [sym_display_math] = ACTIONS(58),
    [sym_comment] = ACTIONS(58),
    [sym_text] = ACTIONS(58),
    [sym_code_block] = ACTIONS(60),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(11), 1,
      anon_sym_STAR,
    ACTIONS(13), 1,
      anon_sym__,
    ACTIONS(96), 2,
      sym_code_block,
      ts_builtin_sym_end,
    ACTIONS(100), 3,
      sym_code_span,
      sym_inline_math,
      sym_text,
    STATE(10), 3,
      sym_bold,
      sym_italic,
      aux_sym_heading_repeat1,
    ACTIONS(98), 5,
      aux_sym_heading_token1,
      sym_command_name,
      anon_sym_LBRACK,
      sym_display_math,
      sym_comment,
  [28] = 6,
    ACTIONS(11), 1,
      anon_sym_STAR,
    ACTIONS(13), 1,
      anon_sym__,
    ACTIONS(102), 2,
      sym_code_block,
      ts_builtin_sym_end,
    ACTIONS(106), 3,
      sym_code_span,
      sym_inline_math,
      sym_text,
    STATE(11), 3,
      sym_bold,
      sym_italic,
      aux_sym_heading_repeat1,
    ACTIONS(104), 5,
      aux_sym_heading_token1,
      sym_command_name,
      anon_sym_LBRACK,
      sym_display_math,
      sym_comment,
  [56] = 6,
    ACTIONS(112), 1,
      anon_sym_STAR,
    ACTIONS(115), 1,
      anon_sym__,
    ACTIONS(108), 2,
      sym_code_block,
      ts_builtin_sym_end,
    ACTIONS(118), 3,
      sym_code_span,
      sym_inline_math,
      sym_text,
    STATE(11), 3,
      sym_bold,
      sym_italic,
      aux_sym_heading_repeat1,
    ACTIONS(110), 5,
      aux_sym_heading_token1,
      sym_command_name,
      anon_sym_LBRACK,
      sym_display_math,
      sym_comment,
  [84] = 6,
    ACTIONS(54), 1,
      anon_sym_STAR,
    ACTIONS(56), 1,
      anon_sym__,
    ACTIONS(96), 1,
      sym_code_block,
    ACTIONS(121), 3,
      sym_code_span,
      sym_inline_math,
      sym_text,
    STATE(13), 3,
      sym_bold,
      sym_italic,
      aux_sym_heading_repeat1,
    ACTIONS(98), 6,
      aux_sym_heading_token1,
      sym_command_name,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      sym_display_math,
      sym_comment,
  [112] = 6,
    ACTIONS(54), 1,
      anon_sym_STAR,
    ACTIONS(56), 1,
      anon_sym__,
    ACTIONS(102), 1,
      sym_code_block,
    ACTIONS(123), 3,
      sym_code_span,
      sym_inline_math,
      sym_text,
    STATE(14), 3,
      sym_bold,
      sym_italic,
      aux_sym_heading_repeat1,
    ACTIONS(104), 6,
      aux_sym_heading_token1,
      sym_command_name,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      sym_display_math,
      sym_comment,
  [140] = 6,
    ACTIONS(108), 1,
      sym_code_block,
    ACTIONS(125), 1,
      anon_sym_STAR,
    ACTIONS(128), 1,
      anon_sym__,
    ACTIONS(131), 3,
      sym_code_span,
      sym_inline_math,
      sym_text,
    STATE(14), 3,
      sym_bold,
      sym_italic,
      aux_sym_heading_repeat1,
    ACTIONS(110), 6,
      aux_sym_heading_token1,
      sym_command_name,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      sym_display_math,
      sym_comment,
  [168] = 4,
    ACTIONS(138), 1,
      anon_sym_LBRACE,
    STATE(23), 1,
      sym_command_arg,
    ACTIONS(134), 2,
      sym_code_block,
      ts_builtin_sym_end,
    ACTIONS(136), 10,
      aux_sym_heading_token1,
      sym_command_name,
      anon_sym_LBRACK,
      anon_sym_STAR,
      anon_sym__,
      sym_code_span,
      sym_inline_math,
      sym_display_math,
      sym_comment,
      sym_text,
  [191] = 4,
    ACTIONS(134), 1,
      sym_code_block,
    ACTIONS(140), 1,
      anon_sym_LBRACE,
    STATE(24), 1,
      sym_command_arg,
    ACTIONS(136), 11,
      aux_sym_heading_token1,
      sym_command_name,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_STAR,
      anon_sym__,
      sym_code_span,
      sym_inline_math,
      sym_display_math,
      sym_comment,
      sym_text,
  [214] = 2,
    ACTIONS(142), 2,
      sym_code_block,
      ts_builtin_sym_end,
    ACTIONS(144), 10,
      aux_sym_heading_token1,
      sym_command_name,
      anon_sym_LBRACK,
      anon_sym_STAR,
      anon_sym__,
      sym_code_span,
      sym_inline_math,
      sym_display_math,
      sym_comment,
      sym_text,
  [231] = 2,
    ACTIONS(148), 1,
      sym_code_block,
    ACTIONS(146), 11,
      aux_sym_heading_token1,
      sym_command_name,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_STAR,
      anon_sym__,
      sym_code_span,
      sym_inline_math,
      sym_display_math,
      sym_comment,
      sym_text,
  [248] = 2,
    ACTIONS(150), 2,
      sym_code_block,
      ts_builtin_sym_end,
    ACTIONS(152), 10,
      aux_sym_heading_token1,
      sym_command_name,
      anon_sym_LBRACK,
      anon_sym_STAR,
      anon_sym__,
      sym_code_span,
      sym_inline_math,
      sym_display_math,
      sym_comment,
      sym_text,
  [265] = 2,
    ACTIONS(154), 2,
      sym_code_block,
      ts_builtin_sym_end,
    ACTIONS(156), 10,
      aux_sym_heading_token1,
      sym_command_name,
      anon_sym_LBRACK,
      anon_sym_STAR,
      anon_sym__,
      sym_code_span,
      sym_inline_math,
      sym_display_math,
      sym_comment,
      sym_text,
  [282] = 2,
    ACTIONS(148), 2,
      sym_code_block,
      ts_builtin_sym_end,
    ACTIONS(146), 10,
      aux_sym_heading_token1,
      sym_command_name,
      anon_sym_LBRACK,
      anon_sym_STAR,
      anon_sym__,
      sym_code_span,
      sym_inline_math,
      sym_display_math,
      sym_comment,
      sym_text,
  [299] = 2,
    ACTIONS(158), 2,
      sym_code_block,
      ts_builtin_sym_end,
    ACTIONS(160), 10,
      aux_sym_heading_token1,
      sym_command_name,
      anon_sym_LBRACK,
      anon_sym_STAR,
      anon_sym__,
      sym_code_span,
      sym_inline_math,
      sym_display_math,
      sym_comment,
      sym_text,
  [316] = 2,
    ACTIONS(162), 2,
      sym_code_block,
      ts_builtin_sym_end,
    ACTIONS(164), 10,
      aux_sym_heading_token1,
      sym_command_name,
      anon_sym_LBRACK,
      anon_sym_STAR,
      anon_sym__,
      sym_code_span,
      sym_inline_math,
      sym_display_math,
      sym_comment,
      sym_text,
  [333] = 2,
    ACTIONS(162), 1,
      sym_code_block,
    ACTIONS(164), 11,
      aux_sym_heading_token1,
      sym_command_name,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_STAR,
      anon_sym__,
      sym_code_span,
      sym_inline_math,
      sym_display_math,
      sym_comment,
      sym_text,
  [350] = 2,
    ACTIONS(168), 1,
      sym_code_block,
    ACTIONS(166), 11,
      aux_sym_heading_token1,
      sym_command_name,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_STAR,
      anon_sym__,
      sym_code_span,
      sym_inline_math,
      sym_display_math,
      sym_comment,
      sym_text,
  [367] = 2,
    ACTIONS(150), 1,
      sym_code_block,
    ACTIONS(152), 11,
      aux_sym_heading_token1,
      sym_command_name,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_STAR,
      anon_sym__,
      sym_code_span,
      sym_inline_math,
      sym_display_math,
      sym_comment,
      sym_text,
  [384] = 2,
    ACTIONS(142), 1,
      sym_code_block,
    ACTIONS(144), 11,
      aux_sym_heading_token1,
      sym_command_name,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_STAR,
      anon_sym__,
      sym_code_span,
      sym_inline_math,
      sym_display_math,
      sym_comment,
      sym_text,
  [401] = 2,
    ACTIONS(158), 1,
      sym_code_block,
    ACTIONS(160), 11,
      aux_sym_heading_token1,
      sym_command_name,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_STAR,
      anon_sym__,
      sym_code_span,
      sym_inline_math,
      sym_display_math,
      sym_comment,
      sym_text,
  [418] = 2,
    ACTIONS(154), 1,
      sym_code_block,
    ACTIONS(156), 11,
      aux_sym_heading_token1,
      sym_command_name,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_STAR,
      anon_sym__,
      sym_code_span,
      sym_inline_math,
      sym_display_math,
      sym_comment,
      sym_text,
  [435] = 2,
    ACTIONS(168), 2,
      sym_code_block,
      ts_builtin_sym_end,
    ACTIONS(166), 10,
      aux_sym_heading_token1,
      sym_command_name,
      anon_sym_LBRACK,
      anon_sym_STAR,
      anon_sym__,
      sym_code_span,
      sym_inline_math,
      sym_display_math,
      sym_comment,
      sym_text,
  [452] = 5,
    ACTIONS(170), 1,
      anon_sym_RBRACK,
    ACTIONS(172), 1,
      anon_sym_STAR,
    ACTIONS(175), 1,
      anon_sym__,
    ACTIONS(178), 1,
      sym_text,
    STATE(31), 3,
      sym_bold,
      sym_italic,
      aux_sym_link_text_repeat1,
  [470] = 5,
    ACTIONS(181), 1,
      anon_sym_RBRACK,
    ACTIONS(183), 1,
      anon_sym_STAR,
    ACTIONS(185), 1,
      anon_sym__,
    ACTIONS(187), 1,
      sym_text,
    STATE(33), 3,
      sym_bold,
      sym_italic,
      aux_sym_link_text_repeat1,
  [488] = 5,
    ACTIONS(183), 1,
      anon_sym_STAR,
    ACTIONS(185), 1,
      anon_sym__,
    ACTIONS(189), 1,
      anon_sym_RBRACK,
    ACTIONS(191), 1,
      sym_text,
    STATE(31), 3,
      sym_bold,
      sym_italic,
      aux_sym_link_text_repeat1,
  [506] = 1,
    ACTIONS(146), 4,
      anon_sym_RBRACK,
      anon_sym_STAR,
      anon_sym__,
      sym_text,
  [513] = 1,
    ACTIONS(156), 4,
      anon_sym_RBRACK,
      anon_sym_STAR,
      anon_sym__,
      sym_text,
  [520] = 2,
    ACTIONS(193), 1,
      anon_sym_LPAREN,
    STATE(30), 1,
      sym_link_url,
  [527] = 2,
    ACTIONS(195), 1,
      anon_sym_LPAREN,
    STATE(25), 1,
      sym_link_url,
  [534] = 1,
    ACTIONS(197), 1,
      anon_sym_LPAREN,
  [538] = 1,
    ACTIONS(199), 1,
      anon_sym_STAR,
  [542] = 1,
    ACTIONS(201), 1,
      anon_sym_RPAREN,
  [546] = 1,
    ACTIONS(203), 1,
      sym_text,
  [550] = 1,
    ACTIONS(205), 1,
      anon_sym_LPAREN,
  [554] = 1,
    ACTIONS(207), 1,
      sym_text,
  [558] = 1,
    ACTIONS(209), 1,
      ts_builtin_sym_end,
  [562] = 1,
    ACTIONS(211), 1,
      anon_sym__,
  [566] = 1,
    ACTIONS(213), 1,
      anon_sym_STAR,
  [570] = 1,
    ACTIONS(215), 1,
      anon_sym__,
  [574] = 1,
    ACTIONS(217), 1,
      aux_sym_link_url_token1,
  [578] = 1,
    ACTIONS(219), 1,
      anon_sym_RPAREN,
  [582] = 1,
    ACTIONS(221), 1,
      anon_sym_STAR,
  [586] = 1,
    ACTIONS(223), 1,
      anon_sym__,
  [590] = 1,
    ACTIONS(225), 1,
      sym_text,
  [594] = 1,
    ACTIONS(227), 1,
      sym_text,
  [598] = 1,
    ACTIONS(229), 1,
      aux_sym_link_url_token1,
  [602] = 1,
    ACTIONS(231), 1,
      sym_text,
  [606] = 1,
    ACTIONS(233), 1,
      sym_text,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(9)] = 0,
  [SMALL_STATE(10)] = 28,
  [SMALL_STATE(11)] = 56,
  [SMALL_STATE(12)] = 84,
  [SMALL_STATE(13)] = 112,
  [SMALL_STATE(14)] = 140,
  [SMALL_STATE(15)] = 168,
  [SMALL_STATE(16)] = 191,
  [SMALL_STATE(17)] = 214,
  [SMALL_STATE(18)] = 231,
  [SMALL_STATE(19)] = 248,
  [SMALL_STATE(20)] = 265,
  [SMALL_STATE(21)] = 282,
  [SMALL_STATE(22)] = 299,
  [SMALL_STATE(23)] = 316,
  [SMALL_STATE(24)] = 333,
  [SMALL_STATE(25)] = 350,
  [SMALL_STATE(26)] = 367,
  [SMALL_STATE(27)] = 384,
  [SMALL_STATE(28)] = 401,
  [SMALL_STATE(29)] = 418,
  [SMALL_STATE(30)] = 435,
  [SMALL_STATE(31)] = 452,
  [SMALL_STATE(32)] = 470,
  [SMALL_STATE(33)] = 488,
  [SMALL_STATE(34)] = 506,
  [SMALL_STATE(35)] = 513,
  [SMALL_STATE(36)] = 520,
  [SMALL_STATE(37)] = 527,
  [SMALL_STATE(38)] = 534,
  [SMALL_STATE(39)] = 538,
  [SMALL_STATE(40)] = 542,
  [SMALL_STATE(41)] = 546,
  [SMALL_STATE(42)] = 550,
  [SMALL_STATE(43)] = 554,
  [SMALL_STATE(44)] = 558,
  [SMALL_STATE(45)] = 562,
  [SMALL_STATE(46)] = 566,
  [SMALL_STATE(47)] = 570,
  [SMALL_STATE(48)] = 574,
  [SMALL_STATE(49)] = 578,
  [SMALL_STATE(50)] = 582,
  [SMALL_STATE(51)] = 586,
  [SMALL_STATE(52)] = 590,
  [SMALL_STATE(53)] = 594,
  [SMALL_STATE(54)] = 598,
  [SMALL_STATE(55)] = 602,
  [SMALL_STATE(56)] = 606,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [21] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [24] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [27] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [30] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [33] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(43),
  [36] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [39] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [42] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [44] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [48] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [50] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [52] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [54] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [56] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [58] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [62] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [64] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [68] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [71] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [74] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [76] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(55),
  [79] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(56),
  [82] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [85] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [88] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [90] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [94] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading, 1, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_heading, 1, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading, 2, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_heading, 2, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_heading_repeat1, 2, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_heading_repeat1, 2, 0, 0),
  [112] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_heading_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [115] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_heading_repeat1, 2, 0, 0), SHIFT_REPEAT(43),
  [118] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_heading_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [121] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [123] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [125] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_heading_repeat1, 2, 0, 0), SHIFT_REPEAT(55),
  [128] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_heading_repeat1, 2, 0, 0), SHIFT_REPEAT(56),
  [131] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_heading_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command, 1, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_command, 1, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [140] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command_arg, 3, 0, 0),
  [144] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_command_arg, 3, 0, 0),
  [146] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_italic, 3, 0, 0),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_italic, 3, 0, 0),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command_arg, 2, 0, 0),
  [152] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_command_arg, 2, 0, 0),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bold, 3, 0, 0),
  [156] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bold, 3, 0, 0),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_link_url, 3, 0, 0),
  [160] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_link_url, 3, 0, 0),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command, 2, 0, 0),
  [164] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_command, 2, 0, 0),
  [166] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_link, 2, 0, 0),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_link, 2, 0, 0),
  [170] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_link_text_repeat1, 2, 0, 0),
  [172] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_link_text_repeat1, 2, 0, 0), SHIFT_REPEAT(52),
  [175] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_link_text_repeat1, 2, 0, 0), SHIFT_REPEAT(53),
  [178] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_link_text_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [181] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [183] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [185] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [187] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [189] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [191] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [197] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_link_text, 2, 0, 0),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [205] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_link_text, 3, 0, 0),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [209] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token_code_block = 0,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token_code_block] = sym_code_block,
};

static const bool ts_external_scanner_states[2][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token_code_block] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_tinylang_external_scanner_create(void);
void tree_sitter_tinylang_external_scanner_destroy(void *);
bool tree_sitter_tinylang_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_tinylang_external_scanner_serialize(void *, char *);
void tree_sitter_tinylang_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_tinylang(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_tinylang_external_scanner_create,
      tree_sitter_tinylang_external_scanner_destroy,
      tree_sitter_tinylang_external_scanner_scan,
      tree_sitter_tinylang_external_scanner_serialize,
      tree_sitter_tinylang_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
