#!/usr/bin/env bash
# Generate THIRD_PARTY_NOTICES.md from Rust and TypeScript dependencies.
# Requires: cargo-license (cargo install cargo-license)
#           pnpm (for TS deps)
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/THIRD_PARTY_NOTICES.md"

{
    echo "# Third-Party Notices"
    echo ""
    echo "This file lists the licenses of all third-party dependencies used by this project."
    echo "Generated on $(date -u +%Y-%m-%d)."
    echo ""

    # ── Rust dependencies ─────────────────────────────────────────────
    echo "## Rust Dependencies"
    echo ""
    if command -v cargo-license &>/dev/null; then
        (cd "$ROOT/rust-core" && cargo license --json 2>/dev/null) | \
            python3 -c "
import json, sys
deps = json.load(sys.stdin)
for d in sorted(deps, key=lambda x: x.get('name', '')):
    name = d.get('name', 'unknown')
    version = d.get('version', '?')
    license = d.get('license', 'Unknown')
    authors = d.get('authors', 'Unknown')
    print(f'- **{name}** v{version} — {license} ({authors})')
" 2>/dev/null || echo "- *(cargo-license output unavailable — install cargo-license)*"
    else
        echo "- *(cargo-license not installed — run \`cargo install cargo-license\`)*"
    fi
    echo ""

    # ── TypeScript dependencies ───────────────────────────────────────
    echo "## TypeScript Dependencies"
    echo ""
    if command -v pnpm &>/dev/null; then
        (cd "$ROOT/extension" && pnpm licenses list --json 2>/dev/null) | \
            python3 -c "
import json, sys
data = json.load(sys.stdin)
for entry in sorted(data, key=lambda x: x.get('name', '') if isinstance(x, dict) else ''):
    if isinstance(entry, dict):
        name = entry.get('name', 'unknown')
        version = entry.get('version', '?')
        license = entry.get('license', 'Unknown')
        print(f'- **{name}** v{version} — {license}')
" 2>/dev/null || echo "- *(pnpm licenses output unavailable)*"
    else
        echo "- *(pnpm not installed)*"
    fi
    echo ""
    echo "---"
    echo "Auto-generated by \`scripts/generate-third-party.sh\`"
} > "$OUT"

echo "Generated $OUT"
